#@TYPE: Machine
#@NAME: generic loongarch64 machine
#@DESCRIPTION: Machine configuration for running a generic loongarch64

require conf/machine/include/loongarch/qemuloongarch.inc

DEFAULTTUNE = "loongarch64"

export ROOTFS_PACKAGE_ARCH = "loongarch64"
PACKAGE_EXTRA_ARCHS:tune-loongarch64 += " longarch64"
require conf/multilib.conf
MULTILIBS ?= ""

DISTRO_FEATURES_DEFAULT:remove = "seccomp"
SED_CONFIG_EFI = ''

