#@TYPE: Machine
#@NAME: generic loongarch64 machine
#@DESCRIPTION: Machine configuration for running a generic loongarch64

require conf/machine/include/loongarch/qemuloongarch.inc

XVISOR_PLAT = "loongarch/virt64"

EXTRA_IMAGEDEPENDS += "u-boot"
UBOOT_MACHINE = "qemu-loongarch64_smode_defconfig"
UBOOT_ELF = "u-boot"

DISTRO_FEATURES_DEFAULT:remove = "seccomp"
SED_CONFIG_EFI = ''
PREFERRED_VERSION_linux-yocto = "6.5%"
GCCVERSION = "13.2%"
PREFERRED_VERSION_glibc = "2.38"
PREFERRED_VERSION_glibc-mtrace = "2.38"
PREFERRED_VERSION_glibc-scripts= "2.38"
PREFERRED_VERSION_glibc-locale = "2.38"
PREFERRED_VERSION_cross-localedef-native = "2.38"
PREFERRED_VERSION_nativesdk-glibc = "2.38"
BINUVERSION = "2.41"
GOVERSION = "1.20.12"
RUSTVERSION = "1.70.0"
#PREFERRED_VERSION_binutils = "2.41"
#PREFERRED_VERSION_binutils-crosssdk-x86_64-pokysdk-linux = "2.41"

